### ISSUE TITLE
Julia Studio no longer start on Windows 8

### ISSUE THREAD

**Issue by JimShaw** [forio/julia-studio#101]
I've been running Julia Studio on a Lenovo U410, under Windows 8, for over a week without a problem.  This morning Julia Studio would not start.  When the Julia Studio icon is doubled clicked or highlighted and Right Click/Open(ed), the julia-release-basic.exe process starts, but Julia Studio does not.

**Comment by WestleyArgentum** [comment]
Hmm. Sounds frustrating, sorry about that.

Have you added or removed any programs or libraries recently?

The first thing you might try is removing the settings folder (you can back it up if you don't want to lose your color settings, etc). On windows 7 the folder would be `C:\Users\your-name\AppData\Roaming\JuliaStudio`, you can just delete or move the whole folder.

Failing that I'd like to know if opening Julia Studio from the command line produces any valuable errors. If you open a command prompt, `cd \path\to\JuliaStudio-version\julia-studio\bin\` and launch `JuliaStudio.exe` that might give us some info.

Have you changed anything else, perhaps shutdown your computer (or not shut down your computer) throughout the week? You could try turning it off and on again and reinstalling Julia Studio.

**Comment by JimShaw** [comment]
Thank you Westley, you saved the day.  Windows 8 doesn't have a settings folder at C:\Users\your-name\AppData\Roaming\JuliaStudio, but it does have a JuliaStudio.ini file.  Once I renamed it, Julia started up correctly.  Thank you for your help.
