### ISSUE TITLE
Calendar.jl problem on Windows 7 & 8

### ISSUE THREAD

**Issue by JimShaw** [forio/julia-studio#102]
"using Calendar" results in an error message:

julia> using Calendar
could not load module libicuuc: The specified module could not be found.

at C:\Users\Jim\AppData\Roaming\julia\packages\ICU\src\ICU.jl:27
at C:\Users\Jim\AppData\Roaming\julia\packages\Calendar\src\Calendar.jl:1

I downloaded libicuuc.dll from several web sites, but could not successfully register any of them.

**Comment by WestleyArgentum** [comment]
I'm not sure Calendar.jl works on windows. On [their page](https://github.com/nolta/Calendar.jl) I see:

```
Calendar.jl requires the International Components for Unicode (ICU) library be installed on your system. It comes preinstalled on OS X and most Linux desktop distributions, but if not:

Arch: pacman -S icu
Fedora: yum install icu
Ubuntu: aptitude install libicu48
```

Try poking them, maybe they have a workaround.

**Comment by WestleyArgentum** [comment]
I see this on the mailing list: https://groups.google.com/forum/?fromgroups=#!searchin/julia-users/calendar$20windows/julia-users/B4bkdDRcxao/1VY5dGdMCFoJ

Maybe something has happened since then

**Comment by JimShaw** [comment]
Thanks again, Westley.  Calendar looks like an excellent package, so if Keno has an early solution for precompiled libraries for Windows, I'd like to try it for him.

**Comment by catawbasam** [comment]
Just FYI Calendar does work on Windows now if you install ICU per @nolta's docs
