### ISSUE TITLE
Bad display in Preferences

### ISSUE THREAD

**Issue by kbrydges** [forio/julia-studio#103]
Hello-
  Testing on Mac 10.6.8/Chrome/Julia 0.3.2, in preferences-text editor-display, the arrows do not work for "Display right margin at Column". Refer to screenshot :)

![PreferenceJuliaIssue](https://f.cloud.github.com/assets/3923808/282744/34fb1414-919b-11e2-9190-e227e5d7dc09.png)

**Comment by WestleyArgentum** [comment]
This works on my osx build, but you have to check the "Display right margin at column" box
