### ISSUE TITLE
ERROR: error compiling Init: error compiling Connect: box: argument is of incorrect size

### ISSUE THREAD

**Issue by epitron** [forio/julia-studio#109]
I just built the latest JuliaStudio from git (under Arch Linux, and using the latest Julia language build from git).

It builds fine, and when I run it, the QT GUI launches and appears to work. However, in GUI's console pane, I get the following output:

```
Initializing package repo for the first time, hold on.

Initialized empty Git repository in /home/epi/.julia/.git/
[master (root-commit) 9a0d15c] Initial empty commit
Cloning into 'METADATA'...
[master 244b6f9] Empty package repo
 3 files changed, 5 insertions(+)
 create mode 100644 .gitmodules
 create mode 160000 METADATA
 create mode 100644 REQUIRE
ERROR: error compiling Init: error compiling Connect: box: argument is of incorrect size
 in Init at /usr/share/qtcreator/juliaengine/sandbox.jl:85
 in include_from_node1 at loading.jl:92
 in process_options at client.jl:253
 in _start at client.jl:332
at /usr/share/qtcreator/juliaengine/main.jl:11
```

There doesn't appear to be anything I can do in the console after this point.

**Comment by epitron** [comment]
Here is the console output from JuliaStudio:

```
$ JuliaStudio 
Title: "Version 0.3" 
Link: "http://forio.com/julia/updates/RelNotes.html" 
Release notes link: "http://forio.com/julia/updates/RelNotes.html" 
Pub. date: "Mon, 25 Feb 2013 00:00:00 +0000" 
Enclosure URL: "http://forio.com/julia/downloads/julia-studio-linux-installer-0.3.1.tar.gz" 
Enclosure version: "0.3.1" 
Enclosure platform: "q_os_linux" 
Enclosure length: 1618935 
Enclosure type: "application/octet-stream" 
Version ' "0.3.1" ' is ignored, too old or something like that. 
```

**Comment by WestleyArgentum** [comment]
I'm trying to repro on this end. If you have time, do you get the same problem with this commit: 4e278ffcd3b254cf75a8a13f3f11c7c267c98d1e ?

**Comment by WestleyArgentum** [comment]
Also, what version of Julia are you using?

**Comment by epitron** [comment]
The Julia version that I'm using is the latest git checkout from yesterday. `julia --version` says "0.2.0", but who knows what that means. :)

The SHA1-ish for the julia commit is gee8eb76.

I can try rebuilding that version you linked later, if that would help...

**Comment by WestleyArgentum** [comment]
Heh, the only important change was in Julia code, so you don't have to really do a rebuild. If you checkout and run again from Qt Creator it should redeploy the julia scripts.

But it's not a big deal, I bet we're just not up to date with the latest Julia changes. Shouldn't be too hard to fix on this end, building as we speak.

**Comment by epitron** [comment]
Ah, I see. Good to know for the future.

It would be nice if someone made updating more efficient. Whenever someone changes 3 lines of C code, the end user usually has to re-download 20 megs of stuff. There should really be something better. (Chromium's executable-diffing system is amazing, but they're fighting some patent lawsuit right now. Someone patented the idea of diffing disassembled code. :)

Anyhow, thanks for testing out the latest build! Julia is a rapidly-evolving moving target right now, and I'm sure it's a pain to deal with this in a big IDE. I just thought you might want the heads-up. I've downloaded the statically built JuliaStudio in the meantime.

**Comment by WestleyArgentum** [comment]
Ok, I just pushed what I hope is a fix. For the record, we really need to replace the julia scripts that run the console. We're working to do so asap.

Let me know if 8a547233dc726d7144ece0a5215a095443e14f0d works

**Comment by epitron** [comment]
Thanks! I'll have to try this a bit later, since I'm not in Linux at the moment.

**Comment by WestleyArgentum** [comment]
Everything cool here? The error had to do with mixing up integer types... I actually think Julia should give a better message, something like "type mismatch"

**Comment by epitron** [comment]
Yep -- works good now!
