### ISSUE TITLE
Julia crashes when navigating through help links

### ISSUE THREAD

**Issue by kbrydges** [forio/julia-studio#110]
When navigating to Help-Technical Support-Documentation-Source(takes you to github), Julia crashes and gives the screenshot below. I can reproduce this by selecting the back arrow when at the "Source" page and then navigating back to the Source page. I have to uninstall it to get it to run again. 

![JuliaCrash](https://f.cloud.github.com/assets/3923808/359609/2bb55f1a-a166-11e2-9d1f-183ef30eec1f.png)

**Comment by keesvp** [comment]
On Windows, no crash, but browser hangs when trying to go to documentation.

**Comment by keesvp** [comment]
Clearly a QT issue. Let's wait for Qt5 port.

**Comment by WestleyArgentum** [comment]
For reference: #141

**Comment by keesvp** [comment]
On Windows, with Qt5, looks good now.

**Comment by keesvp** [comment]
We changed the help menu's so that we no longer use browser widgets inside Julia Studio, so this issue looses most, if not all, relevance.

**Comment by stuinzuri** [comment]
no longer relevant
