### ISSUE TITLE
Is integrating Debug.jl into Julia Studio feasible ?

### ISSUE THREAD

**Issue by wlbksy** [forio/julia-studio#111]
It would be of great help to have debug functionality.
Besides that, call `whos()` when in interactive debugging status, can provide us a simple Matlab-like workspace

**Comment by WestleyArgentum** [comment]
I really want to say that we can get on that, debugging is clearly a huge weak point for us, but I don't think it's going to happen in the immediate future.

Time is the main problem... but the technical challenge would be interfacing with Debug.jl from the console in JuliaStudio. We talk to our console over a tcp connection and, as I understand it, Debug.jl expects to be able to use stdin / stdout. We are going to replace the console with a better written one soon, but it will still use tcp.

Truth be told though, I'm not that familiar with Debug.jl. So there might be something simple I'm missing.

**Comment by wlbksy** [comment]
I know little of tcp or socket programming.

I was thinking if we could press some button, and the IDE would insert corresponding debugging macro into the Julia source code which we want to debug. However, it seems has its own limitation

> @debug can only be used in global (i.e. module) scope

Seems we need a native debugging support from Julia.

**Comment by ViralBShah** [comment]
Cc: @toivoh

**Comment by toivoh** [comment]
The stdin/stdout issue shouldn't be a big concern. Their usage is restricted to a minor part of the code, https://github.com/toivoh/Debug.jl/blob/master/src/UI.jl.  It should be straightforward to refactor the code to be able to accept either stdin/stdout, or your tcp connection. Pull requests welcome!

**Comment by adambom** [comment]
@toivoh that's great news. Debugging is a feature that people request quite often. Possibly something @bensadeghi could work on?

**Comment by bensadeghi** [comment]
I'll start looking into it.

**Comment by ViralBShah** [comment]
Cc: @loladiro

**Comment by Keno** [comment]
I have ideas for native debugging support in julia and have done a little exploratory work in that direction, though I'm gonna be incredibly busy for the next two weeks, so I won't really have time to discuss this in-depth until after. Looking forward to tackling this then though.

**Comment by stuinzuri** [comment]
Because of @loladiro's efforts, @keesvp will take the high road and implement a 'real debugger' via LLDB, Qt Creator, etc...and not use Debug.jl.  Closing.
