### ISSUE TITLE
German Keyboard Layout Cannot type "[" or "]"

### ISSUE THREAD

**Issue by adambom** [forio/julia-studio#112]
alt-5 & alt-6  does not help, neither on an ASUS-  nor on a Samsung- notebook (both with Windows 7).  By pressing the original "[" -keys I have no reaktion at all.,

**Comment by adambom** [comment]
"on a french windows, in julia studio 0.3.1,

it is not possible to type A = {1,2}
qt console refuse to type ""{"" (Alt +4) on a french keyboard

in the basic julia terminal (julia.bat) it works without trouble
"

**Comment by stuinzuri** [comment]
Related to #112 ?  Making a priority, we can't limit uses to US keyboard.  I've brought my old Swiss CH-DE keyboard into the office for dev purposes.
