### ISSUE TITLE
Problem with windows xp sp3

### ISSUE THREAD

**Issue by Staross** [forio/julia-studio#114]
When starting Julia studio I get the following in the console, and starting a script (F5) doesn't seem to do anything. The error message comes back after reseting the console. 

0x017C0205 (0x00000000 0x00000000 0x0023FE28 0x6F40B44D) <unknown module>
0x017C01CB (0x019DAAB8 0x00000000 0x00000000 0x00000000) <unknown module>
0x6F40B44D (0x019DA948 0x00000000 0x00000000 0x77C35C94), jl_apply_generic() + 0x5D bytes(s)
0x00401888 (0x00000001 0x000362D4 0x0000007F 0x00000008)
0x6F44131F (0x00000001 0x000362D4 0x00401760 0x77C2C42E), julia_trampoline() + 0x4F bytes(s)
0x00404625 (0x00000001 0x000362D4 0x00033450 0xE7534000)
0x004013EA (0x8981F7BE 0x01CE3E7B 0x7FFD5000 0xC000001D)
0x7C81776F (0x004014D0 0x00000000 0x7C809AF1 0x000061B8), RegisterWaitForInputIdle() + 0x49 bytes(s)

**Comment by WestleyArgentum** [comment]
Sorry for the delay, having trouble finding a copy of xp to test with ;)

Are you pointing at the version of Julia that came with the ide? It should be located in a folder called "julia" at the root of your install location.

Also, does vanilla Julia run alright? You can run check by running "julia.bat" (that should be in the "julia" directory mentioned above).

**Comment by Staross** [comment]
I just checked and it's vanilla Julia related, it's not a julia studio problem. I'll report to them. Sorry for the troubles!

**Comment by WestleyArgentum** [comment]
For you future dwellers: https://github.com/JuliaLang/julia/issues/2921
