### ISSUE TITLE
Can't insert special characters with AltGr in the prompt

### ISSUE THREAD

**Issue by waldyrious** [forio/julia-studio#115]
In my keyboard layout some useful characters need to be typed using the AltGr key, e.g. `[` (AltGr+8) and `]` (AltGr+9). In JuliaStudio (v0.3.1, Windows), however, nothing happens if I press these combinations in the prompt, although in other places (in the main edit area, or the filter box) they work normally. A workaround is to type them elsewhere and copy them to the prompt, but that's clearly inadequate.

**Comment by adambom** [comment]
Possibly related to #112 ?

**Comment by waldyrious** [comment]
Maybe. I use a Portuguese layout, and the 3rd level modifier key is `AltGr`, not `Alt`, so I can't say for sure the issue is the same.

**Comment by adambom** [comment]
Ok. In the near future we're going to upgrade the version of QT creator, which has fixed a great many issues. Hopefully that will help.

**Comment by stuinzuri** [comment]
We've got a CH-DE keyboard in the office now and will resolve this soon.  Bumping to priority.
