### ISSUE TITLE
Julia Interpreter does not execute

### ISSUE THREAD

**Issue by MarkCWirt** [forio/julia-studio#125]
Environment: Ubuntu 11.10
                    Julia Studio, compiled from source
                    julia, compiled from source

I recently compiled Julia Studio from source (this was necessary as QT 4.8.0 was a prerequisite, whereas Ubuntu 11.10 is QT 4.7 based, but I had a parallel install of 4.8.4). Everything compiled OK, and once I told Studio where to find julia, everything seems to start up fine, giving no errors.

The issue is that I can't seem to run julia, be it from the run button, F5, or choosing to do so from the menu. The console pops up (if it is closed), but it remains mute, producing no output. If I hit the console clear button I see the julia prompt, but I never see any kind of output.

Thank you.

**Comment by MarkCWirt** [comment]
I don't know if this is relevant, but when I start julia studio I see the following process:

/installPath/julia/bin/julia-release-basic /installPath/share/qtcreator/juliaengine/main.jl

This process pegs the CPU at 100% even when nothing is happening, and this seems like strange behavior.

Looking at the files in that directory, I noticed that consolelogic.jl requires itself at about line 64. I don't speak julia yet (that's why I downloaded the IDE), so I don't know how julia should handle self-referential includes, but when I comment out that line, the interpreter starts.

**Comment by WestleyArgentum** [comment]
I'm glad you were able to get everything built, I'm really surprised that the self require caused (and removing it solved?) a problem.

The file requiring itself is for running Julia on multiple cores, it just ensures that the code get's loaded onto each... but much of this logic has been re-written for the better and we intend to integrate it soon.

Are you up and running? And is your built version of Julia v 0.1 or 0.2? I wouldn't be surprised if running with 0.2 is a bit bumpy right now, but we do have full support planned soon.

**Comment by MarkCWirt** [comment]
Thanks Westley -- yes, I'm up and running now.

Yes, removing the line did fix things for me. A git diff shows that to be the only change I made:

---

mark@lucid:/usr/really-local/julia-studio$ git diff
diff --git a/share/qtcreator/juliaengine/consolelogic.jl b/share/qtcreator/juliaengine/conso
index 2c30aa2..3e4f10e 100644
--- a/share/qtcreator/juliaengine/consolelogic.jl
+++ b/share/qtcreator/juliaengine/consolelogic.jl
@@ -61,7 +61,7 @@ module __ConsoleLogic
 import __Sandbox
 import __Event

-require("consolelogic.jl")
+#require("consolelogic.jl")

---

If you'd like any more information for ferreting out what's happening (such as hardware platform, etc), let me know.

As for my julia version, I cloned the master repository a few days ago, so it's probably pretty much bleeding edge (last commit was 27 May). Latest tag was v0.1.2.

Thanks again!

**Comment by WestleyArgentum** [comment]
Not at all, thank you for reporting.

We'll take note of this when we shift to shipping Julia 0.2
