### ISSUE TITLE
question - run Julia parallel in Julia Studio?

### ISSUE THREAD

**Issue by marksale** [forio/julia-studio#126]
Is it possible to launch Julia parallel (Julia -p 4) from Julia studio?
thanks
Mark
mesale@iu.edu

**Comment by WestleyArgentum** [comment]
Try `addprocs(num)`, I think that should do it.

**Comment by marksale** [comment]
Thanks (again)

--- On Tue, 5/28/13, Westley Argentum Hennigh notifications@github.com wrote:

**Comment by marksale** [comment]
Thanks for you help:
I tried that:
addprocs(3)
both at command prompt from a file

got this:

addprocs not defined

at C:/julia/parallel/parallel.jl:1

I'm running  0.3.1 on Windows 7, 64 bit

thanks
Mark

**Comment by WestleyArgentum** [comment]
Oh, my bad, the ide ships with the Julia 0.1, `addprocs` is from the 0.2 candidate.

You want `addprocs_local`, I do believe

**Comment by marksale** [comment]
Thanks, I think that did it
Mark

**Comment by WestleyArgentum** [comment]
Cool. Let us know if you have any trouble, tentatively I'll close this.
