### ISSUE TITLE
Problem on startup

### ISSUE THREAD

**Issue by adambom** [forio/julia-studio#127]
When I start JS, I get this message in the console (OSX 10.8)

dyld: Library not loaded: @rpath/libjulia-release.dylib
  Referenced from: /Users/Adam/code/julia/bin/julia-release-basic
  Reason: image not found
Error: Julia crashed unexpectedly.
It's still a young language, this can happen from time to time.
Please reset the console and try again...

**Comment by WestleyArgentum** [comment]
I think this was probably an issue on windows caused by a missing sys0.ji. Much has changed since this was filed; for anyone looking at this in the future: check out issue #139
