### ISSUE TITLE
Support for Julia 0.2+?

### ISSUE THREAD

**Issue by randyzwitch** [forio/julia-studio#129]
Using JuliaStudio 0.3.2 for OSX, I get the following error when I point to my local julia installation.  Is there a way to fix this error? Using OSX terminal, when I cd to the directory I list in the Julia Studio path to binaries section it works, so my path is correct.

``` julia
ERROR: AbstractKind not defined
 in include_from_node1 at loading.jl:91
 in reload_path at loading.jl:114
 in require at loading.jl:48
 in include_from_node1 at loading.jl:91
 in reload_path at loading.jl:114
 in require at loading.jl:48
 in include_from_node1 at loading.jl:91
 in process_options at client.jl:251
 in _start at client.jl:324
at /Applications/JuliaStudio.app/Contents/Resources/juliaengine/sandbox.jl:9
at /Applications/JuliaStudio.app/Contents/Resources/juliaengine/network.jl:1
at /Applications/JuliaStudio.app/Contents/Resources/juliaengine/main.jl:2

```

**Comment by WestleyArgentum** [comment]
The latest Julia Studio master is compatible with Julia 0.2, but we haven't released an update to the ide yet.

In a pinch, you might be able to clone this repo and copy the contents of "./share/qtcreator/juliaengine" into "JuliaStudio.app/Contents/Resources/juliaengine". Or you could always build from source.

**Comment by randyzwitch** [comment]
Thanks, that did it!

Separate question...is there a shortcut command to submit highlighted code from the text editor, instead of just using F5 to submit the entire file?

**Comment by WestleyArgentum** [comment]
There isn't but that is oft requested... I'm going to close this but you should submit an issue for that
