### ISSUE TITLE
Opening .jlp file crashes the editor

### ISSUE THREAD

**Issue by adambom** [forio/julia-studio#13]
If you open a .jlp file it crashes julia studio

**Comment by WestleyArgentum** [comment]
As soon as you get a chance, show this to me. I cannot repro

**Comment by WestleyArgentum** [comment]
Scratch that, I figured out what you mean

**Comment by WestleyArgentum** [comment]
Fixed in 5455738c7907d1519d1aa9d2b949036232785962. 

.jlp is no longer a thing (but opening a random .jlp file wont crash the editor anymore either)
