### ISSUE TITLE
Directory navigation coupled to command line

### ISSUE THREAD

**Issue by timholy** [forio/julia-studio#132]
I've been watching a new user learn the console version of Julia to process data files. From my perspective, the most awkward challenges have to do with changing directories and inputting file names, exacerbated by the fact that currently copy-paste don't work in the Windows REPL. I wonder if these are aspects of his experience that might be greatly improved with Julia Studio. It would seem that a few features---which may be present already but I did not discover on my own---would make a big difference:
- Is it possible to have the current location in the "File System" pane coupled to the Julia command line's idea of `pwd()`? A right-click "Set as current directory" would be sufficient.
- Might one be able to copy-paste a filename from the "File System" pane as a string into the command line?
- (Low priority) It does not seem possible to change drives without invoking "Choose folder..."

**Comment by WestleyArgentum** [comment]
These are all good ideas, thanks for posting.

A quick note on the first one: changing directories does happen, but it's tied to the file currently being edited (which seems not to be what people expect, so it may change). In other words, if you browse in the "File System" pane the command line stays put, but as soon as you open a file the console changes to that files directory (and if you have multiple editor panes open it will stay in sync with whatever you're editing).

**Comment by timholy** [comment]
> as you open a file the console changes to that files directory

Ah, that is useful in many cases. However, for "data files" it's unlikely that the user will want to open them in an editor. I'm working with some 4TB image files...

**Comment by WestleyArgentum** [comment]
Haha, ya, that probably wouldn't go over well. I think enough people have had issues with the current approach that it's worth changing.
