### ISSUE TITLE
Pkg.add() not working on windows

### ISSUE THREAD

**Issue by rogerjbos** [forio/julia-studio#135]
I am trying to add the ODBC package (or ANY package) and the folder and source code never gets added to my packages folder.  For example if add ODBC it never creates a ODBC folder in C:\Users\bosr\AppData\Roaming\julia\packages
I also get a bunch of warnings, but those seem okay as METADATA does have all the appropriate folders with what looks like reasonable git data.

Here is the output:

julia> Pkg.dir()
"C:\Users\bosr\AppData\Roaming\julia\packages"

julia> adding ODBC
cygwin warning:
  MS-DOS style path detected: METADATA\ASCIIPlots\versions
  Preferred POSIX equivalent is: METADATA/ASCIIPlots/versions
  CYGWIN environment variable option "nodosfilewarning" turns off this warning.
  Consult the user's guide for more details about POSIX paths:
    http://cygwin.com/cygwin-ug-net/using.html#using-pathnames
cygwin warning:
  MS-DOS style path detected: METADATA\ApproxFun\versions
  Preferred POSIX equivalent is: METADATA/ApproxFun/versions
  CYGWIN environment variable option "nodosfilewarning" turns off this warning.
  Consult the user's guide for more details about POSIX paths:
    http://cygwin.com/cygwin-ug-net/using.html#using-pathnames
cygwin warning:
  MS-DOS style path detected: METADATA\ArgParse\versions
  Preferred POSIX equivalent is: METADATA/ArgParse/versions
  CYGWIN environment variable option "nodosfilewarning" turns off this warning.
  Consult the user's guide for more details about POSIX paths:
    http://cygwin.com/cygwin-ug-net/using.html#using-pathnames
cygwin warning:
  MS-DOS style path detected: METADATA\BSplines\versions
  Preferred POSIX equivalent is: METADATA/BSplines/versions
  CYGWIN environment variable option "nodosfilewarning" turns off this warning.
  Consult the user's guide for more details about POSIX paths:
...
...
...
cygwin warning:
  MS-DOS style path detected: METADATA\GARCH\versions
  Preferred POSIX equivalent is: METADATA/GARCH/versions
  CYGWIN environment variable option "nodosfilewarning" turns off this warning.
  Consult the user's guide for more details about POSIX paths:
    http://cygwin.com/cygwin-ug-net/using.html#using-pathnames

julia>

**Comment by rogerjbos** [comment]
Deleting the C:\Users\bosr\AppData\Roaming\julia\packages folder and starting over resolved the problem with Pkg.add, but I was never able to get ODBC to work with Julia Studio, but it works with regular Julia.

**Comment by WestleyArgentum** [comment]
Sorry about not responding.

Are you using the Julia binaries that come with the IDE or did you build yourself? Our binary distribution is quite old at this point, but @keesvp and I are going to be updating it asap. I think the new package manager will solve most problems of this nature.

**Comment by rogerjbos** [comment]
Yes, I was using the old binary distribution.  It would be nice if the Julia Studio editor was separate from the Julia language so that one could use any or multiple versions of Julia with Julia Studio.

**Comment by WestleyArgentum** [comment]
It actually is, and you can, but changes on both ends have been so volatile that it's not really feasible in practice.

If you go to Tools->Options->Julia you can specify the location of a Julia build. Unfortunately the julia scripts that come with the ide and allow it to talk to a julia terminal don't run inside Julia-0.2. If you pull the latest changes from github and replace the "juliaengine" script files it's usually possible to get it to work, but that's obviously a bit hacky and, like I said, we're finally about to start pushing out updates again :)

**Comment by rogerjbos** [comment]
That's really interesting.  Thanks for sharing the tip and thanks for all your work on Julia Studio.
