### ISSUE TITLE
Error when changing for Julia version 

### ISSUE THREAD

**Issue by Staross** [forio/julia-studio#136]
I changed the julia path in the option to update to a newer julia version (2.0) and here is what I get:

ERROR: AbstractKind not defined
 in include at boot.jl:238
 in include_from_node1 at loading.jl:96
 in reload_path at loading.jl:121
 in require at loading.jl:50
 in include at boot.jl:238
 in include_from_node1 at loading.jl:96
 in reload_path at loading.jl:121
 in require at loading.jl:50
 in include at boot.jl:238
 in include_from_node1 at loading.jl:96
 in process_options at client.jl:274
 in _start at client.jl:349
at C:\Program Files\JuliaStudio-0.3.1\julia-studio\share\qtcreator\juliaengine\sandbox.jl:9
at C:\Program Files\JuliaStudio-0.3.1\julia-studio\share\qtcreator\juliaengine\network.jl:1
at C:\Program Files\JuliaStudio-0.3.1\julia-studio\share\qtcreator\juliaengine\main.jl:2

**Comment by WestleyArgentum** [comment]
Unfortunately the build of Julia Studio up for download is quite outdated. @keesvp and I are going to push an update soon, but I think the fixes you need are already in github (if you can build from source).

**Comment by Staross** [comment]
A new build would be sweet, I tried to build it from sources but it didn't worked. Not everybody knows how to build stuff, especially on windows.

**Comment by WestleyArgentum** [comment]
Hey, I'm going to close this and point you towards issue #139
