### ISSUE TITLE
browsing symbolic links is broken on windows

### ISSUE THREAD

**Issue by WestleyArgentum** [forio/julia-studio#137]
Following a symbolic link to a folder will take you nowhere and leave you with an empty white box where the file tree should be

**Comment by keesvp** [comment]
It's not nice, but again easily corrected/avoided by using right-click Choose Folder

**Comment by keesvp** [comment]
It turns out these files are regarded by the file system filter as hidden files rather than symbolic links. I will fix this by default not showing hidden files, but install a toggle to show them.
