### ISSUE TITLE
erroneously escaped character gives ugly error in JSON

### ISSUE THREAD

**Issue by keesvp** [forio/julia-studio#144]
For instance when you mistakenly type \ instead of /

**Comment by kbrydges** [comment]
QA note: validated in on Mac. It returns "unsupported or misplaced expression break" when I type in an unsupported special character.

**Comment by ifed1** [comment]
julia> \
\ (generic function with 46 methods)

julia> julia\romeo\//\/\/\/\/\
unsupported or misplaced expression break

Verified on win7(64-bit).
