### ISSUE TITLE
parsing strings gives julia error in json parser

### ISSUE THREAD

**Issue by keesvp** [forio/julia-studio#146]

**Comment by ifed1** [comment]
[3014, 8.56, 6.5, 10.75, 8.5] / [3014, 8.56, 6.5, 10.75, 8.5]
5x5 Array{Float64,2}:
 0.999967    0.00283998  0.00215653  0.00356657  0.00282008
 0.00283998  8.06578e-6  6.12472e-6  1.01293e-5  8.00925e-6
 0.00215653  6.12472e-6  4.65078e-6  7.69167e-6  6.08179e-6
 0.00356657  1.01293e-5  7.69167e-6  1.27208e-5  1.00583e-5
 0.00282008  8.00925e-6  6.08179e-6  1.00583e-5  7.95311e-6

Verified in win7(64-bit)
