### ISSUE TITLE
Not running simple tutorial examples

### ISSUE THREAD

**Issue by lrsantos11** [forio/julia-studio#149]
Guys,

I'm trying to do all tutorials you put on Julia Studio and I cannot run the Quadratic tutorial.
I even download the tutorials from github
Seems that it cannot find the quadratic.jl nor the derivative.jl.
The example runs well on Terminal with Julia.
Any ideia of what is happening?

Best Regards,

Rafa

**Comment by keesvp** [comment]
Most likely it's a Julia path issue. For the moment to keep going you can manually run the required function files in 'reverse' order. (In this case derivative.jl -> quadratic.jl -> main.jl. I agree it's awkward, but I'll look into making it better.

**Comment by spayne** [comment]
I'm running into the same problem.  Some incompatibility with require() and how julia-studio works. 

Here is a test case.  On Windows using the 0.4 version of Julia Studio:
1. Using File/New, create a file called myconstants.jl.  
2. In editor, add a constant const ME = 5.97e24 to this file
3. In Console, type require("myconstants.jl") 
4. type ME

Observed Behaviour:
julia> ME
ME not defined

Expected Behaviour (from a terminal session):
julia> ME
5.97e24

**Comment by mkriele** [comment]
Just to confirm that this is not just a windows issue.  I am running into the same problem on Mac with the binary 0.4.1 for OSX 10.7 or later (the corrected version that was posted yesterday evening). I previously did this example on 0.3.2 (or 0.3.1, not sure) and it worked well.   

In my experience it does not seem to have anything to do with the order in which the files are required. However, if you change "required" to "include" the example worlds.  (keesvp, is this what you meant?)  

I also have noticed that (after Reset) the calculation takes a coupe of seconds.

**Comment by lrsantos11** [comment]
I forgot to say I was testing on a OSX 10.8 (Mountain Lion) as well as on a
OSX 10.7 (Lion)

Best Regards,

Rafael

---

Luiz Rafael dos Santos
Skype: lrsantos11
Twitter: @lrsantos11

**Comment by keesvp** [comment]
I am on it. I found out something changed in Julia handling includes and requires. Posted on their group and Github, waiting for answers.

**Comment by stuinzuri** [comment]
@keesvp Could you post a link?  I'd be interested in following the details.

**Comment by keesvp** [comment]
https://groups.google.com/forum/?hl=en#!topic/julia-dev/NQcHJP3hV2k
I also posted here https://github.com/JuliaLang/julia/issues but it doesn't show up yet.

**Comment by keesvp** [comment]
that would be https://github.com/JuliaLang/julia/issues/4567

**Comment by JeffBezanson** [comment]
Generally for just "loading" a source file you want `include`. `require` is rarely used explicitly anymore, since it is called internally by `using` and `import`.

**Comment by lrsantos11** [comment]
Great.
Kees, someone should modify the tutorial.

Cheers Jeff. Thanks for that.

Rafa

---

Luiz Rafael dos Santos
Skype: lrsantos11
Twitter: @lrsantos11

**Comment by keesvp** [comment]
The downloadable tutorial code is corrected. The website still needs work.

**Comment by keesvp** [comment]
This has long been done.
