### ISSUE TITLE
dynamic auto-complete based on contents of open files

### ISSUE THREAD

**Issue by WestleyArgentum** [forio/julia-studio#150]
I'm not sure how hard this would be, but I've come to love auto-complete based on the contents of files. The basic idea is to parse a file using basic syntactic knowledge (mostly about how to break up words, like "thing.member" etc), then suggest completions based on that data. It's never perfect, but it's a huge time saver.

**Comment by stuinzuri** [comment]
There is talk on in the Julia repo about this, by using the auto documentation behind help().  See https://github.com/JuliaLang/julia/issues/4579 in julia rep.

**Comment by ivarne** [comment]
Julia will change their REPL implementation and I think that they will factor out all the autocompletion code into https://github.com/loladiro/REPLCompletions.jl. The best approach will probably be to collaborate there. The first issue (https://github.com/loladiro/REPLCompletions.jl/issues/4) is to find a good API and julia-studio probably have some input.

**Comment by WestleyArgentum** [comment]
Thanks for that! I hadn't caught that conversation

**Comment by adambom** [comment]
That would only work in cases where the JIT had already compiled the open file, wouldn't it?

**Comment by ivarne** [comment]
That will depend on how the interface is designed. I'm certain that
contributions to enable this kind of functionality will be welcome
Den 7. nov. 2013 19:39 skrev "Adam Savitzky" notifications@github.com
følgende:
