### ISSUE TITLE
Julia-Studio 0.4 crashes on Mac OS 10.6

### ISSUE THREAD

**Issue by WestleyArgentum** [forio/julia-studio#151]
Many people have reported this issue in the last two days, I'm creating this issue to try and help get out the solution.

Briefly: we now offer two versions for OSX, one for 10.6 and one for 10.7+

Please visit http://forio.com/julia/downloads/ and grab the version that suites you best!

**Comment by staticfloat** [comment]
@WestleyArgentum We have recently provided 10.6 builds for nightly Julia builds as well!  I'm curious what you do for 10.6 that's different!

**Comment by WestleyArgentum** [comment]
@staticfloat Heh, actually our builds are the same but we bundle the two different versions of Julia that you produce :)

A couple days ago when we released 0.4 I didn't realize that the Julia build we bundled wouldn't work on 10.6

**Comment by staticfloat** [comment]
Ah, I see.  The 10.6/10.7+ distinction is thanks to a some work we did on the profiler for OSX: It uses some symbols that aren't available on 10.6, so the backtraces don't work quite as well on 10.6, but at least it runs. :)
