### ISSUE TITLE
Issues installing js0.4 and 0.41 with Mac running OSX 10.6.8

### ISSUE THREAD

**Issue by feierbach** [forio/julia-studio#152]
Dyld Error Message:
  Library not loaded: /Users/westley/QtSDK/Desktop/Qt/4.8.1/gcc/lib/QtWebKit.framework/Versions/4/QtWebKit
  Referenced from: /Applications/JuliaStudio.app/Contents/MacOS/JuliaStudio
  Reason: image not found

Went to QT site and found Qt 4.8.1 not compatible with OSX 10.6 and later.
Earlier version of Julia ran fine.

**Comment by WestleyArgentum** [comment]
Wow... it looks like a path to the Qt libraries on my system got baked in somewhere.

Thanks for reporting this, I'll start looking into it right away. We've got another user in-house who's been able to run this and other builds of Julia Studio on 10.6, so I'm confident that we can get Qt 4.8.1 working.

**Comment by WestleyArgentum** [comment]
@feierbach, have you used a previous version of Julia Studio?

**Comment by feierbach** [comment]
Hi Westley, Thanks for looking into this. Yes I have used the version that was available about 3 to 4 weeks ago. I didn't record the version number but should have. When I got upgrade message I did it without thinking I should have saved the prior version without blinking. It would have been simple to save the downloaded package. Since this software is so new it would have been the thing to do.

**Comment by WestleyArgentum** [comment]
Hey! So it looks like I failed to include a few required binaries in the builds that were on the website earlier today. I've updated them now, could you try downloading and installing again? Sorry for the trouble, I think it will work this time!

**Comment by feierbach** [comment]
Westley, Took a while to download this time but all is now well. Thanks for all the work to get me back on track. 
As a footnote, do you know if anyone has Julia running on the Adapteva Parallella. http://www.adapteva.com/products/parallella/parallella/
The new Mac that will be released before the end of the year will have 7 teraflops of processing capability if Julia will be able to access the GPUs. http://macpro.macrumors.com/

**Comment by WestleyArgentum** [comment]
I'm not sure, but I would love to see that happen :) I think a friend of mine has an order in for one of the Parallella boards.

Try starting a topic on the user mailing list: https://groups.google.com/group/julia-users, someone might have some work to share
