### ISSUE TITLE
64-bit Linux version?

### ISSUE THREAD

**Issue by IainNZ** [forio/julia-studio#153]
I tried running JuliaStudio on my 64bit Ubuntu 12.04 machine but it wouldn't start.
It looks like its a 32-bit executable - should it work?

**Comment by WestleyArgentum** [comment]
Yes, it should... You may have to do something to run it in 32bit compatibility mode.

But I don't think we've updated our linux binaries in a long time, so they'll still come with Julia-0.1 and an old version of the ide. We would like to put together a debian package and not mess around with hosting a bunch of different linux binaries, but no one has gotten around to it yet...

**Comment by edsfocci** [comment]
I've verified that it works on my 64-bit Xubuntu 12.04. IainNZ, can you tell me more about what you are doing in your attempt to install and run JuliaStudio on your computer?

What I did was unzip this file:
http://forio.com/julia/downloads/julia-studio-linux-installer-0.3.1.tar.gz
From here:
http://forio.com/julia/downloads/

To run it from a GUI file manager, go into the folder named "julia-studio-0.3.1", go into the folder named "bin", and double-click "JuliaStudio", and it should run.

To run it on the terminal, go into the folder named "julia-studio-0.3.1":
cd julia-studio-0.3.1

Then, run the program:
./bin/JuliaStudio

Another thing to check is if you have permissions to run JuliaStudio, and make sure it is set as executable.

**Comment by IainNZ** [comment]
So I'm now on a different 64-bit computer, and still nothing happens when I double-click the application (this one is Ubuntu 13.04 with XMonad window manager).

Similarly to my laptop:

```
idunning@IAIN-DESKTOP:~/.../julia-studio-0.3.1/bin$ ./JuliaStudio
bash: ./JuliaStudio: No such file or directory
idunning@IAIN-DESKTOP:~/.../julia-studio-0.3.1/bin$ ./JuliaStudio.sh
./JuliaStudio.sh: 35: exec: ./JuliaStudio: not found
idunning@IAIN-DESKTOP:~/.../julia-studio-0.3.1/bin$ ls -l JuliaStudio* 
-rwxrwxr-x 1 idunning idunning 182786 Mar  5  2013 JuliaStudio
-rwxrwxr-x 1 idunning idunning    952 Dec  6  2012 JuliaStudio.sh
```

**Comment by edsfocci** [comment]
Hmmm, is there any output to the terminal when you run it there? Try running "JuliaStudio.sh"?

**Comment by IainNZ** [comment]
If you look closely, that's the second thing I do.

**Comment by edsfocci** [comment]
Ok, sorry, I'm very confused, as they are present in the folder, but JuliaStudio executable can't be found? It is a new one to me.

Btw, I'm not one of the developers, just a guy trying to lend a helping hand.

**Comment by IainNZ** [comment]
Ah ok, cool. I think its a 32bit/64bit issue, to be honest. e.g. http://stackoverflow.com/questions/3949161/no-such-file-or-directory-but-it-exists/3949268#3949268

More stuff:

```
idunning@IAIN-DESKTOP:~/.../julia-studio-0.3.1/bin$ readelf -h JuliaStudio
ELF Header:
  Magic:   7f 45 4c 46 01 01 01 00 00 00 00 00 00 00 00 00 
  Class:                             ELF32
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              EXEC (Executable file)
  Machine:                           Intel 80386
  Version:                           0x1
  Entry point address:               0x8053640
  Start of program headers:          52 (bytes into file)
  Start of section headers:          141256 (bytes into file)
  Flags:                             0x0
  Size of this header:               52 (bytes)
  Size of program headers:           32 (bytes)
  Number of program headers:         9
  Size of section headers:           40 (bytes)
  Number of section headers:         31
  Section header string table index: 28
```

**Comment by WestleyArgentum** [comment]
Small update, we've got a new linux build you can download that comes with Julia-rc2. Still 32bit, but you might have better luck running it in compatibility mode

**Comment by stuinzuri** [comment]
I've started on a 64-bit build this morning.  We should have a dedicated distribution in the next few days.

**Comment by gatohaus** [comment]
A-ha.  Looks like I've got the same problem.
Ubuntu 12.04 64b

<pre>
> ./bin/JuliaStudio
bash: ./bin/JuliaStudio: No such file or directory
> 
> ls -l ./bin/JuliaStudio
-rwxrwxr-x 1 david david 182786 Nov  5 17:47 ./bin/JuliaStudio
>
</pre>

Maybe I'll try compiling from source..

**Comment by stuinzuri** [comment]
@gatohaus : in my efforts to get the 0.4.4 release out, I've documented building on Ubuntu 12.04 64-bit at https://github.com/forio/julia-studio/blob/master/linux-build.md

These instructions should work flawlessly for you.  If it weren't for the GUI install of Qt 5.1 it would be a full on script.  Please let me know if you run into a problem.

**Comment by gatohaus** [comment]
Sweet success using your instructions!  Thank you very much.

Just fyi..  I did  not  have qt installed prior to this on my ubuntu 12.04 LTS 64 bit system.  I kept my previously installed version of julia,  0.2.0~precisefinal1   which came from the ubuntu repository, rather than installing the latest build.
One trivial problem with instructions:    define  qtbase  before using it.   ;-)

**Comment by stuinzuri** [comment]
@gatohaus Thanks for the tip.  I've only tested these instructions on 'clean' systems to date.  Will get the docs tested and amended soon.

**Comment by stuinzuri** [comment]
64-bit Ubuntu 12.04 built, tested and distributed.

(32-bit next!)

**Comment by gatohaus** [comment]
@stuinzuri   Just tried the 64bit from the download page..   worked great!  Thanks.
(Ubuntu 12.04 LTS 64bit)
