### ISSUE TITLE
Unsupported or misplaced expression `break`

### ISSUE THREAD

**Issue by ihnorton** [forio/julia-studio#157]
JS 0.4.1, Win64

```
function np(v)
       for i = 1:length(v)
       v[i] = v[i] / norm(v)
       end
       end
```

`Syntax error: Unsupported or misplaced expression break`

reported by one of the attendees at @mlubin's talk today. Oddly enough, he was able to work around it by adding semicolons at the end of each line.

**Comment by WestleyArgentum** [comment]
Strange, I can't repo this on OSX. Tried both pasting the code in and writing it out line by line. @keesvp, what about you?

**Comment by keesvp** [comment]
Looks like I can repro this by typing in the console with shift-enter. I'll look into it.

**Comment by ihnorton** [comment]
Yeah, he just told me that he used shift-enter.

**Comment by keesvp** [comment]
Yes, got it. The lines are glued to close together. If you start each line with a space, it's OK. I'll fix it.

**Comment by ihnorton** [comment]
Thanks!

On Tue, Oct 29, 2013 at 6:54 PM, Kees van Prooijen <notifications@github.com
