### ISSUE TITLE
Cutting and pasting special characters in Windows (7 (32 bit) ,checking on 64 bit and WIndows 8)

### ISSUE THREAD

**Issue by kbrydges** [forio/julia-studio#158]
I tried going to http://german.typeit.org/ and cutting and pasting special characters into Julia Studio Windows 32 bit build 4.2 and it causes user to need to reset the console with error "EOF while attempting to read a string"

examples of special characters that fail:
ü, ß, ú,€

In Mac (10.6), I cut and pasted the same special characters and it worked fine.

**Comment by keesvp** [comment]
Seems to have been fixed along the way. Please check again.

**Comment by kbrydges** [comment]
This looks to be working now.
