### ISSUE TITLE
Console does not run ~/.juliarc.jl on startup (Windows 0.4.2)

### ISSUE THREAD

**Issue by JasonPries** [forio/julia-studio#165]
This is fairly annoying as I use it to modify my LOAD_PATH when Julia is launched.

When I navigate to the path of the Julia binaries I provide to Julia Studio and run the julia batch file directly, everything works as expected.

**Comment by keesvp** [comment]
Thanks for reporting this. I can confirm your findings, and will look into it.

**Comment by keesvp** [comment]
By default Julia will only read .juliarc.jl when started in repl mode. I will add argument '-F' when starting julia for Julia Studio to force reading it at startup.
