### ISSUE TITLE
Windows - updating Julia Studio to an uptodate version keeps the files for the old version of Julia Studio, uninstalling old version does not remove all files

### ISSUE THREAD

**Issue by kbrydges** [forio/julia-studio#168]
In the case where there is already a version of JuliaStudio installed on Windows but a new version is available, the update will install the files for the new version and keep the files for the old version (causing two versions of JuliaStudio to be installed). This appears to mess up the uninstall of the older version (going into older Julia Studio folder and selecting "Uninstall JuliaStudio"). This uninstall does not completely remove the files for the older version.

**Comment by keesvp** [comment]
I could reproduce this, except for the manual uninstall of the older version. That worked cleanly for me, removing everything from the program files directory. Short term solution is, in the update dialog, prompting the user to manually uninstall the old version.

**Comment by keesvp** [comment]
This should be fixed with the next release. New installers will silently auto-uninstall existing installations.
