### ISSUE TITLE
missing tracebacks in REPL

### ISSUE THREAD

**Issue by ggggggggg** [forio/julia-studio#173]
So lets say I'm editing a file called example.jl and it looks like

```
function foo(a)
    4+4
    5+5
    bar(5)
    3+3
end

foo(5)
```

If I run that by pressing F5 I get an ok traceback.  It has a line number, but not a function name.

```
julia> example
bar not defined
at /Users/username/Julia/example.jl:8
```

After running it, if I then go to the REPL command line and type `foo(5)` I get a traceback missing key information, like what function the problem occurred in and the line number.  I can see how reporting a line number may be tricky if I have edited the function since last pressing F5, but certainly I'd like to see at least the function name.

```
julia> foo(5)
bar not defined
```

I pasted the foo function into the default Julia REPL in an OSX terminal and I get a better traceback, with both line number and function name.

```
julia> foo(5)
ERROR: bar not defined
 in foo at none:4
```

This is in Julia Studio 0.4.3 on OSX 10.9. I guess it is a repeat of #113 and #100 , but with more info.

**Comment by WestleyArgentum** [comment]
Thanks for looking into this and reporting! This surely points to a problem with the way we use `showerror` in our console, possibly we're mangling the context or something.
