### ISSUE TITLE
Winston package not working ?

### ISSUE THREAD

**Issue by shazz** [forio/julia-studio#174]
Hello,

I did not find the JuliaStudio limitations so may that's ok.
When I use plot() from Winston package, instead of opening a graph window, the console says : 

FramedPlot(...)

If I missed something, tell me =)

**Comment by WestleyArgentum** [comment]
To see your plot in Julia Studio you first need to render and save it as a png. Probably what you want to do is `file(p, "myplot.png")`

Check out Winston's examples and documentation here: https://github.com/nolta/Winston.jl

**Comment by shazz** [comment]
So there is no way, as it is the case in the standard Julia shell to open a popup and show the plot (without calling file() )? 

File output is somewhat ok but less interactive than the instant popup...

**Comment by WestleyArgentum** [comment]
You're right, it's definitely not ideal... Eventually we want to have stronger integration with plotting tools, probably we will try something along the lines of #148 and see where that takes us.

Sorry for the inconvenience, the one thing I can say for the file plotting is that when you have `myplot.png` from above open, and you regenerate it, it will reload automatically

**Comment by dhruvbhatia** [comment]
Thanks @WestleyArgentum - I was trying to figure out how to use PyPlot with Julia Studio, so that's a handy workaround.

One can simply have `test.png` open in Preview and run code like this within Julia Studio:

```
using PyPlot
pygui(false)

# Save plot as p
p = plot(x, y, color="red", linewidth=5.0, linestyle="--", title="Test")

# Save p as test.png
file(p, "test.png")
```

**Comment by FigiMon** [comment]
I tried the following and it brings up the plot window without having to save to file:

using Winston
x = linspace(1,10);
y = x.^2;

p = plot(x, y);

display(p)
