### ISSUE TITLE
UI too crammed in Preferences -> Help -> General (OS X 10.7)

### ISSUE THREAD

**Issue by AllanLRH** [forio/julia-studio#182]
Title and screensot says it all, along with this info:

``` plain
Julia Studio 0.4.3 
Based on Qt 4.8.1 (64 bit)

Built on Nov 18 2013 at 10:41:18
```

![screen shot 2014-01-12 at 21 36 50](https://f.cloud.github.com/assets/2641327/1897049/56d6f0b2-7bc9-11e3-9dde-ffe59c5e5946.png)

**Comment by keesvp** [comment]
Thanks for reporting this. This issue will probably be solved with the, very soon to be released, next version, which is based on Qt5. We'll keep an eye out for this particular problem

Kees

**Comment by keesvp** [comment]
It's not solved with Qt5, but we reorganized all help functionality, so this menu is redundant and will be removed in the near future.
