### ISSUE TITLE
Ubuntu 12.04 install problem

### ISSUE THREAD

**Issue by welsberr** [forio/julia-studio#183]
I got the Ubuntu Julia Studio install. Running ./bin/JuliaStudio.sh shows the following in the GUI console:

```
fatal: error thrown and no exception handler available.
ErrorException("error compiling _start: error compiling check_blas: error compiling blas_vendor: could not load module libopenblas: libopenblas: cannot open shared object file: No such file or directory")
```

I've installed the libopenblas-dev package. That did not help.

I noticed that libopenblas.so is in ./julia/lib/julia, so I tried adding that directory to the LD_LIBRARY_PATH definition. That did not help.

I noticed that libopnblas.so.0 is a symbolic link that was set to an absolute path on some developer's machine. I deleted that and created a symbolic link to the libopenblas.so file in the ./julia/lib/julia directory. That did not help.

The LD_LIBRARY_PATH variable I ended up with was

```
/home/redacted/bin/julia-studio-0.4.2/lib:/home/redacted/bin/julia-studio-0.4.2/lib/qtcreator:/home/redacted/bin/julia-studio-0.4.2/julia/lib/julia
```

Here is the final run console output:

```
./JuliaStudio.sh
QSqlDatabase: QSQLITE driver not loaded
QSqlDatabase: available drivers: 
Warning: Failed to open settings database at "/home/redacted/.config/JuliaStudio/JuliaStudio.db" ("Driver not loaded")
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x0
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x0
QSqlDatabase: QSQLITE driver not loaded
QSqlDatabase: available drivers: 
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x0
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x0
Title: "Version 0.4.2" 
Link: "http://forio.com/julia/updates/RelNotes.html" 
Release notes link: "http://forio.com/julia/updates/RelNotes.html" 
Pub. date: "Fri, 25 Oct 2013 19:20:11 +0000" 
Enclosure URL: "https://s3.amazonaws.com/cdn-common.forio.com/julia-studio/0.4.2/julia-studio-linux-installer-0.4.2.tar.gz" 
Enclosure version: "0.4.2" 
Enclosure platform: "q_os_linux" 
Enclosure length: 1618935 
Enclosure type: "application/octet-stream" 
Version ' "0.4.2" ' is ignored, probably OK. 
QSqlDatabase: QSQLITE driver not loaded
QSqlDatabase: available drivers: 
QSqlDatabase: QSQLITE driver not loaded
QSqlDatabase: available drivers: 
```

I've probably overlooked something simple, but I'm not seeing it at the moment.

**Comment by stuinzuri** [comment]
That looks like a Julia error and not something specific to Julia Studio.  Could you please try to start Julia at the command line and report back what you get?  

Also, can you please let us know if you are on 32-bit or 64-bit linux?

**Comment by WestleyArgentum** [comment]
It's a bit of a shot in the dark, but running `sudo apt-get install git gfortran glpk fftw3` might help

**Comment by welsberr** [comment]
On 01/13/2014 11:15 AM, Stu Thompson wrote:

> That looks like a Julia error and not something specific to Julia 
> Studio. Could you please try to start Julia at the command line and 
> report back what you get?
> 
> Also, can you please let us know if you are on 32-bit or 64-bit linux?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/forio/julia-studio/issues/183#issuecomment-32183606.

Running from the Julia directory within the Julia Studio install:

fatal: error thrown and no exception handler available.
ErrorException("error compiling _start: error compiling check_blas: 
error compiling blas_vendor: could not load module libopenblas: 
libopenblas: cannot open shared object file: No such file or directory")

So, yes, Julia is having a problem. However, it is the Julia install 
included with Julia Studio, so this is at least a packaging issue with 
the Julia Studio installation.

Result of "uname -a":

Linux gandalf 3.5.0-45-generic #68~precise1-Ubuntu SMP Wed Dec 4 
16:18:46 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

**Comment by welsberr** [comment]
On 01/13/2014 02:33 PM, Westley Argentum Hennigh wrote:

> It's a bit of a shot in the dark, but running |sudo apt-get install 
> git gfortran glpk fftw3| might help
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/forio/julia-studio/issues/183#issuecomment-32202497.

Thanks, but I had already found that advice and tried it without 
improvement.

On a personal note, people keep adding a "t" to my name. Hopefully, you 
don't have a bunch of people dropping the "t" from yours, though it 
would indicate some sort of symmetry.

**Comment by welsberr** [comment]
Given Stu Thompson's insight that Julia and not Julia Studio was having the problem, I took another stab at a workaround.

I installed the Ubuntu package for Julia.

In Tools -> Options -> Julia, I set "Path to Julia binaries" to
/usr

After doing that, Julia Studio runs and the Julia prompt comes up in the console. I can add packages and run programs. But I have completely eliminated the Julia Studio supplied version of Julia from having any part in that. I think that it would be a worthy goal to have the Julia Studio installation work without the kind of workaround I just applied. Therefore I am not closing this issue.

As alternative solutions are suggested, I can set the directory to restore the Julia Studio version of Julia, then apply and test them.

**Comment by stuinzuri** [comment]
@welsberr Our intent is to make Julia a prerequisite of a Julia Studio package, which should go a long way towards a) preventing issues like yours and b) making installations more distribution specific and hence easier to install.

Thanks for reporting your problems and following up.  It is appreciated.  

Stu

**Comment by WestleyArgentum** [comment]
As for names, I used to find that people dropped the "t" a lot, but lately I've noticed people adding it even when I drop it from my pronunciation for simplicity sake... So maybe we've identified some cultural trend :)

But I think @stuinzuri is right: very soon we'd like to distribute Julia Studio as a package and, in that case, it doesn't make much sense for us to be rolling up versions of Julia that get bundled with the ide. Better to depend on the standard, maintained package and ensure that the IDE is flexible enough to work with different versions of Julia.
