### ISSUE TITLE
Copying and pasting a selection of code into the console does not work (doesn't work with comments, multiple lines of code)

### ISSUE THREAD

**Issue by kbrydges** [forio/julia-studio#184]
Cutting and pasting multiple lines into the console does not work, it seems to be failing with comments:

example of code I tried in the console:
using DataFrames
using Distributions
using PyPlot
using GLM
# =====================================================================

N = 20 # Training set size
true_w = [-0.3 0.5 -0.9] # The answer
s² = 0.2^2 # Variance of noise

**Comment by keesvp** [comment]
This is as good as fixed, but not in time for 0.4.4

**Comment by keesvp** [comment]
Correction, it's in 0.4.4! Released today.
