### ISSUE TITLE
Cannot use non-ANSI characters: "unsupported or misplaced expression break"

### ISSUE THREAD

**Issue by joyofdata** [forio/julia-studio#186]
Julia Studio 0.4.3 64bit:

```
julia> "ä"
unsupported or misplaced expression break
```

Julia 0.2.0 64bit console:

```
julia> "ä"
"\204"
"\u84"
```

I would like to simply use any UTF-8 character in strings and have them displayed in output.

How do I resolve this issue?

Windows 8 Pro 64bit (German)

---

Maybe this issue is related to an issue I opened for julia also about problems with characters beyond ANSI or ASCII.
[https://github.com/JuliaLang/julia/issues/5461]

**Comment by keesvp** [comment]
Thanks for reporting this. As you can see we had problems like this before. I'll get onto it asap.

**Comment by joyofdata** [comment]
thanks for the info!

**Comment by keesvp** [comment]
OK, I think I fixed this. Unfortunately we are on the verge of publishing  0.4.4, so look for 0.4.5 to see this fixed.

**Comment by joyofdata** [comment]
Looking very much forward to it!

**Comment by keesvp** [comment]
Managed to get it in 0.4.4 after all. Released today.
