### ISSUE TITLE
Can't download the update - error in webpage - Linux version 0.4.4

### ISSUE THREAD

**Issue by eugenio** [forio/julia-studio#188]
The download link : 
https://s3.amazonaws.com/cdn-common.forio.com/julia-studio/0.4.4/julia-studio-linux-64-0.4.4.tar.gz
leads to a broken page where only a xml document resides.

**Comment by WestleyArgentum** [comment]
Apologies, that bundle was never marked as publicly available. It should work now!

**Comment by keesvp** [comment]
Thanks Wes.
