### ISSUE TITLE
Error on Julia studio 0.4.4 with ubuntu 13.10 

### ISSUE THREAD

**Issue by eugenio** [forio/julia-studio#191]
ERROR: could not open file /opt/Julia_Studio/share/qtcreator/juliet/src/modules/network/../../../../JSON/src/JSON.jl
 in include at boot.jl:238
at /opt/Julia_Studio/share/qtcreator/juliet/src/modules/network/network.jl:4
at /opt/Julia_Studio/share/qtcreator/juliet/src/Juliet.jl:29
at /opt/Julia_Studio/share/qtcreator/Console/Console.jl:2

When pointing to the correct julia binary in system path i get the former error.

**Comment by stuinzuri** [comment]
Thanks for reporting this.

Could you please give me a bit more background?  Was this error on startup?  Or were you writing Julia code, importing packages, etc.?  

Regardless, we have not yet tested on Ubuntu 13.10 so there may be an issue.  I'll get to that this week.

**Comment by thotypous** [comment]
The case of the `JSON` directory is wrong in the distributed binary package.

```
mv /opt/Julia_Studio/share/qtcreator/json /opt/Julia_Studio/share/qtcreator/JSON
```

**Comment by eugenio** [comment]
I can confirm that the above command fixes the issue, you can close it, thanks!

**Comment by stuinzuri** [comment]
I think I know why this happened--I added the readme file on my mac, and tar'd up from there.   This is probably an issue for other upper case dirs/folders and needs fixing ASAP.

**Comment by stuinzuri** [comment]
I've updated the tar file, this won't be a problem for anyone going forward.  There may be more support issues though.
