### ISSUE TITLE
Build fails on Linux

### ISSUE THREAD

**Issue by gpmauroy** [forio/julia-studio#193]
My environment:
$ cat /proc/version
Linux version 3.10.24-desktop-2.mga3 (iurt@jonund.mageia.org) (gcc version 4.7.2 (GCC) ) #1 SMP Fri Dec 13 20:34:53 UTC 2013

qmake -r is successful.

make then fails as follows:

FV_APP_NAME=\"JuliaStudio\" -DFV_APP_VERSION=\"0.4.4\" -DQT_NO_DEBUG -DQT_WEBKIT_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/lib64/qt4/mkspecs/linux-g++ -I. -I/usr/include/QtCore -I/usr/include/QtNetwork -I/usr/include/QtGui -I/usr/include/QtWebKit -I/usr/include -I../../src -I../libs -I/home/gilles/src/julia-studio/tools -I../plugins -I../shared/qtsingleapplication -I../shared/qtlockedfile -I../../fervor -I.moc/release-shared -I.uic -o .obj/release-shared/fvupdatewindow.o ../../fervor/fvupdatewindow.cpp
In file included from ../../fervor/fvupdatewindow.cpp:2:0:
.uic/ui_fvupdatewindow.h:24:29: fatal error: QtWebKit/QWebView: No such file or directory
compilation terminated.

**Comment by stuinzuri** [comment]
Hum.  Can you please confirm the version of Qt you are running?

**Comment by gpmauroy** [comment]
$ qmake --version
QMake version 2.01a
Using Qt version 4.8.5 in /usr/lib64

**Comment by stuinzuri** [comment]
Yea, so that's the problem.  The dependency is on Qt 5.1.0.  I've whipped up Linux build instructions that spell out step by step how to build Julia Studio which will take you through step-by-step.

https://github.com/forio/julia-studio/blob/master/linux-build.md

**Comment by gpmauroy** [comment]
OK, thanks.
I have installed Qt 5.1.0 as indicated and got all other listed dependencies I could find -- i.e., all except build-essential that does not seem to apply to my RPM system.

Now, I am getting the following error when running make (qmake -r is successful):
g++ -Wl,-z,origin '-Wl,-rpath,/opt/Qt5.1.0//5.1.0/gcc_64:$ORIGIN:$ORIGIN/..:$ORIGIN/../lib/qtcreator' -Wl,-O1 -Wl,-rpath,/opt/Qt5.1.0/5.1.0/gcc_64/lib -shared -Wl,-soname,libAggregation.so.1 -o libAggregation.so.1.0.0 .obj/release-shared/aggregate.o .obj/release-shared/moc_aggregate.o  -L/home/gilles/src/julia-studio/lib/julia-studio -L/opt/Qt5.1.0//5.1.0/gcc_64/lib -lQt5Widgets -lQt5Concurrent -lQt5Gui -lQt5Core -lGL -lpthread  
/usr/bin/ld: cannot find -lGL
collect2: error: ld returned 1 exit status

$ qmake --version
QMake version 3.0
Using Qt version 5.1.0 in /opt/Qt5.1.0//5.1.0/gcc_64/lib

$ ld --version
GNU ld (Linux/GNU Binutils) 2.23.51.0.8.20121218

$ g++ --version
g++ (GCC) 4.7.2

Any idea?
Thanks.
