### ISSUE TITLE
All builds -Incomplete commands in the console are no longer giving an error message

### ISSUE THREAD

**Issue by kbrydges** [forio/julia-studio#196]
In the 0.4.3 build for Mac, an error would happen if a user put an incomplete command in the the console, for example:

```
julia> 2 + 
unsupported or misplaced expression break
```

In the 4.4 build for Mac, this error is no longer happening, nothing is returned when an incomplete command is entered.

**Comment by keesvp** [comment]
This was due to a bug in Julia. Fixed with current 0.3.0-prerelease.
