### ISSUE TITLE
Problem with directory structure, qtcreator missing.

### ISSUE THREAD

**Issue by aelg** [forio/julia-studio#197]
I have built julia-studio from source on a Ubuntu 12.04 system. Followed the guide in the linux_build.md except the optional qtchooser part.
Build is fine but when running julia-studio.sh I got the error:

```
Failed to load core: Could not find 'Core.pluginspec' in /home/username/julia-studio/lib/qtcreator/plugins,/home/username/.local/share/data///JuliaStudio/juliastudio/plugins/0.4.4
```

Seems that the qtcreator directory is renamed to julia-studio. Adding a symlink in julia-studio/lib (qtcreator -> julia-studio) solves this and the GUI starts.
When starting the GUI reports the following error:

```
QProcessPrivate::execChild() failed to chdir to /home/linustemp/julia-studio/share/qtcreator/Console
ERROR: could not open file /home/linustemp/julia-studio/share/qtcreator/Console/Console.jl
 in include_from_node1 at loading.jl:120
```

Same error again namechange from qtcreator to julia-studio, but in julia-studio/share this time, adding a symlink fixes this and everything seems to be working fine (this time the directory qtcreator exists with a single directory json in it, simply removing this qtcreator and replacing it with the symlink seems to work). 

I'm guessing there is some configuration somewhere that is wrong, but I don't know where. Probably related to this merge https://github.com/forio/julia-studio/pull/180 ?

**Comment by WestleyArgentum** [comment]
Yes, this is almost certainly because of #180.

We'll need to do testing on a linux machine. I might be able to create one and try sometime this week, but if someone with a machine already set up could poke at it that would be awesome

**Comment by stuinzuri** [comment]
I'll do it on my VM later this week and grab you when stuck.

**Comment by aelg** [comment]
Did some grepping and found some stuff. After applying the following things seem to work.

```
diff --git a/src/app/main.cpp b/src/app/main.cpp
index 15b77a7..1cf6605 100644
--- a/src/app/main.cpp
+++ b/src/app/main.cpp
@@ -201,7 +201,7 @@ static inline QStringList getPluginPaths()
     QString pluginPath = rootDirPath;
     pluginPath += QLatin1Char('/');
     pluginPath += QLatin1String(IDE_LIBRARY_BASENAME);
-    pluginPath += QLatin1String("/qtcreator/plugins");
+    pluginPath += QLatin1String("/julia-studio/plugins");
     rc.push_back(pluginPath);
 #else
     // 2) "PlugIns" (OS X)
@@ -281,7 +281,7 @@ static inline QSettings *userSettings()
 #ifdef Q_OS_MAC
 #  define SHARE_PATH "/../Resources"
 #else
-#  define SHARE_PATH "/../share/qtcreator"
+#  define SHARE_PATH "/../share/julia-studio"
 #endif

 int main(int argc, char **argv)
diff --git a/src/plugins/coreplugin/icore.cpp b/src/plugins/coreplugin/icore.cpp
index a9a1de9..b1102ab 100644
--- a/src/plugins/coreplugin/icore.cpp
+++ b/src/plugins/coreplugin/icore.cpp
@@ -487,7 +487,7 @@ QString ICore::userInterfaceLanguage()
 #ifdef Q_OS_MAC
 #  define SHARE_PATH "/../Resources"
 #else
-#  define SHARE_PATH "/../share/qtcreator"
+#  define SHARE_PATH "/../share/julia-studio"
 #endif

 QString ICore::resourcePath()
```

Changes in src/app/main.cpp fixes the first error and src/plugins/coreplugin/icore.cpp the second.
The change to SHARE_PATH in src/app/main.cpp is not necessary, but feels like it should be there?

**Comment by aelg** [comment]
Sorry for closing, wrong button.

**Comment by WestleyArgentum** [comment]
@stuinzuri can you double check on linux?

**Comment by stuinzuri** [comment]
@WestleyArgentum gimme 30m

**Comment by aelg** [comment]
Seems like the commit above don't change pluginPath in main.cpp. Maybe I was a little unclear but that change is necessary. The other change in main.cpp to SHARE_PATH is not. Can't test until tomorrow since I'm on another computer right now.

**Comment by keesvp** [comment]
I checked that in earlier separately. Everything works for Windows now. Hope it's good for Linux too.

**Comment by stuinzuri** [comment]
I was able to compile with the state from two hours ago.  I'll pull again and retest.  (Clean 32-bit Ubuntu 12.04.3)

**Comment by aelg** [comment]
master HEAD works for me now.
