### ISSUE TITLE
Provide Functionality in editor to highlight a select number of lines of code and use a keystroke to run those lines of code 

### ISSUE THREAD

**Issue by kbrydges** [forio/julia-studio#210]

**Comment by keesvp** [comment]
You could try copying the code fragment in the console.

**Comment by randyzwitch** [comment]
Duplicate to https://github.com/forio/julia-studio/issues/130

**Comment by WestleyArgentum** [comment]
@randyzwitch good catch - sorry that it looks like your post went unanswered :/

**Comment by randyzwitch** [comment]
No problem @WestleyArgentum, I'm sure it will be added at some point. :)
