### ISSUE TITLE
QLabel.h is called instead of qlabel.h

### ISSUE THREAD

**Issue by jlhouchin** [forio/julia-studio#214]

**Comment by jlhouchin** [comment]
My apologies I don't know what happened. I left this in an open window and when I return it appears to have been submitted.

The julia-studio/src/plugins/projectexplorer/sessiondialog.cpp file says
#include <QLabel.h>

when it should be
#include <qlabel.h> 

according to the Qt5.1 install downloaded via the link on the Linux install page.

**Comment by keesvp** [comment]
Thanks, I've changed it to <QLabel>.
