### ISSUE TITLE
Remove About Plugins... Option

### ISSUE THREAD

**Issue by adambom** [forio/julia-studio#22]
In the Julia Studio menu, remove the About Plugins... option

**Comment by WestleyArgentum** [comment]
What did the About Plugins option ever do to you?

No, but seriously, it should be there.
1) If our stuff breaks people need to be able to switch out the version of the plugin used.
2) If other plugins are broken or the user accidentally breaks them then they need acces to that menu.
3) People will have their own plugins for qt creator, why would we stop them from using them?
