### ISSUE TITLE
Path to Julia binaries does not work

### ISSUE THREAD

**Issue by ntagg** [forio/julia-studio#223]
I went to Preferences > Julia and updated the Path to Julia binaries to the actual path to the binaries on my Mac (OSX 10.9.3).  The binaries are installed to the default path from the Julia installer (I'm using Julia 0.2.1).  The path is: "/Applications/Julia-0.2.1.app/Contents/Resources/julia/bin"

After saving this, I get the following console error:

```
Error: Failed to start Julia.
Expected location: /Applications/Julia-0.2.1.app/Contents/Resources/julia/bin/bin/julia-basic
```

I reverted back to the original path that was the prior value, and continued to get this error (now with the old path).

**Comment by Andy-P** [comment]
Your problem might be that your path setting includes all the way to `bin` rather than the `julia` folder one level above. Your error shows you have `/bin/bin/`. 

Try changing this:

```
  "/Applications/Julia-0.2.1.app/Contents/Resources/julia/bin"
```

to this:

```
  "/Applications/Julia-0.2.1.app/Contents/Resources/julia"
```
