### ISSUE TITLE
Preferences: Remove these options

### ISSUE THREAD

**Issue by adambom** [forio/julia-studio#23]
Remove Environment Tab
Text Editor: Remove Snippets, Macros, and Completion
Remove FakeVim tab
Remove C++ tab
Remove QT Quick tab
Give the Julia tab an icon
Remove Build and Run tab
Remove version control tab (for now anyway)
Remove Code Pasting tab

**Comment by WestleyArgentum** [comment]
Done for now, we can remove / add stuff as needed
