### ISSUE TITLE
Issue with modules ConsoleLogic and Event

### ISSUE THREAD

**Issue by ivanlai** [forio/julia-studio#242]
Hi,

My OS: Ubuntu 12.04 32 bit
Julia version 0.3.0

I get the following error messages in the output console after re-installing Julio-Studio today

ERROR: type UnitRange has no field len
 in on_complete_msg at /home/ivan/julia-studio/share/julia-studio/Console/ConsoleLogic.jl:210
 in handle_input at /home/ivan/julia-studio/share/julia-studio/Console/ConsoleLogic.jl:229
 in anonymous at /home/ivan/julia-studio/share/julia-studio/Console/ConsoleLogic.jl:246
 in handle_pending_events at /home/ivan/julia-studio/share/julia-studio/juliet/src/modules/event/event.jl:84
 in update at /home/ivan/julia-studio/share/julia-studio/juliet/src/modules/event/event.jl:59
 in event_loop at /home/ivan/julia-studio/share/julia-studio/juliet/src/modules/event/event.jl:72
 in run at /home/ivan/julia-studio/share/julia-studio/juliet/src/juliet-engine.jl:48
 in include at ./boot.jl:245
 in include_from_node1 at loading.jl:128
 in process_options at ./client.jl:285
 in _start at ./client.jl:354
 in _start_3B_1697 at /usr/bin/../lib/i386-linux-gnu/julia/sys.so
while loading /home/ivan/julia-studio/share/julia-studio/Console/Console.jl, in expression starting on line 21

Thanks.

**Comment by keesvp** [comment]
This Julia Studio is not compatible with 0.3.0. You have to wait for 0.4.5 or build from source.
