### ISSUE TITLE
Is there any command to type that shows all the odes that exist in ODE.jl package in Julia?

### ISSUE THREAD

**Issue by Lytu** [forio/julia-studio#255]
As i said in the title, i would like to know if there is a command in JULIA that shows all the odes (ode23, ode45, ...) in ODE.jl package. 
Is there any documentation that details all these odes and their equivalent in MATLAB ?

**Comment by WestleyArgentum** [comment]
Hey, I see that you've opened a few different issues about ODE.jl here -- just so you know, it's usually better to ask either the package maintainers themselves (https://github.com/JuliaLang/ODE.jl) or on the users mailing list (https://groups.google.com/forum/#!forum/julia-users)

In this specific case though, I think you're looking for `julia> whos(ODE)`

**Comment by Lytu** [comment]
Thank you

**Comment by Lytu** [comment]
How can i have the package maintainer's e-mail so that i can ask them some questions, is anyone know how to contact them? Thank you

**Comment by WestleyArgentum** [comment]
The link I sent before is to a github repository like this one, but for that project: https://github.com/JuliaLang/ODE.jl

You can search through past issues there, and file new ones. If you're just looking to ask questions though, please use: https://groups.google.com/forum/#!forum/julia-users
