### ISSUE TITLE
Factorize a matrix using the NMF package

### ISSUE THREAD

**Issue by Lytu** [forio/julia-studio#256]
NMF.jl package can factorize a matrix 3x3 and give two matrix (a 3x2 matrix H and a 2x3 matrix W), W is the transpose of a matrix H?
        A = H \* W
E.g: 
import NMF
A=[5.0 3.0 6.0;3.0 9.0 12.0;6.0 12.0 17.0]
H,  W= NMF.randinit(A, 2)

this code give me 2 matrix H and W

I know that NMF.randinit() gives two matrix H(3x2) and W(2x3) but W is not the transpose of a matrix H.

I would like to know there is a function in NMF package that can give this such result: 
A = H \* W   with  W=H'
Thank you

**Comment by WestleyArgentum** [comment]
As I mentioned on the other issue, I think this might be a better question for the users group (https://groups.google.com/forum/#!forum/julia-users) or the package maintainers (https://github.com/JuliaStats/NMF.jl)

Sorry!
