### ISSUE TITLE
Issues with tout,yout=ODE.ode4((t,x)->functionName(t,x),t,x) in julia version 0.3.6

### ISSUE THREAD

**Issue by Lytu** [forio/julia-studio#257]
I have issues with : 
tout,yout=ODE.ode4((t,x)->functionName(t,x),t,x)
it gives the error: BoundsError() in julia version 0.3.6 but works perfectly in julia version 0.3.0.

Can someone tell me how to fix this problem please?
Thank you

**Comment by WestleyArgentum** [comment]
This seems like it might be a bug in ODE.jl, please check out the repo here: https://github.com/JuliaLang/ODE.jl
