### ISSUE TITLE
ode23s not defined

### ISSUE THREAD

**Issue by Lytu** [forio/julia-studio#258]
What do i do when i have error: ode23s not defined   when i try to use it?
E.g: t,y = ODE.ode23s((t,x)->f(t,x),[0:0.1:1],x)
I have the version 0.3.0 of Julia.

is there anyway to have a list of all odes that exist in ODE package?

Thanks

**Comment by WestleyArgentum** [comment]
closing in favor of https://github.com/forio/julia-studio/issues/255
