### ISSUE TITLE
Which command in julia that permit us to see the implementation of a module/function?

### ISSUE THREAD

**Issue by Lytu** [forio/julia-studio#260]
Is there a command in julia that enables us to see/show the implementation of a module or a function in julia?
If yes, which command? 
Can we modify the code of an existing module/function?

**Comment by WestleyArgentum** [comment]
I believe you're looking for the `@edit` macro: http://docs.julialang.org/en/release-0.3/stdlib/base/?highlight=%40edit#Base.@edit

This repository isn't for the Julia language though, just this IDE. These questions should really be asked in the users group: https://groups.google.com/forum/#!forum/julia-users. When they're asked here, no one (except me and and maybe a few other wandering souls...) will come across them.
