### ISSUE TITLE
JuliaStudio@Ubuntu14.04.1 initialization failed

### ISSUE THREAD

**Issue by ShinkaNao** [forio/julia-studio#264]
I just built JuliaStudio at Ubuntu14.04.1 immediately .
When I use the following command to start JuliaStudio,

①cd julia-studio-master/build/bin
②./julia-studio.sh

JuliaStudio's interface seems to be started, but the initialization failed.
The details of the error are:

ERROR: LoadError: UndefVarError:  require not defined
 in include_from_nodel(::String) at ./loading.jl:488
 in process_options(::Base.JLOptions) at ./client.jl:265
 in _start() at ./client.jl:321
while loading /home/shangzhenhua/julia-studio-master/build/julia-studio-linux-x86_64/share/julia-studio/Console/Console.jl, in expression starting on line 5

Console.jl the wrong line 5 is :
require("../juliet/src/Juliet.jl")

How can I solve this mistake?

Thank you.

**Comment by wglasshusain** [comment]
Unfortunately, Forio no longer supports Julia Studio, although perhaps you may hear suggestions from others in the community.

A good alternative is Juno -- you can download it at http://junolab.org/ .

**Comment by ShinkaNao** [comment]
@wglasshusain Thank you for your answer!
