### ISSUE TITLE
Version 0.2.3 - Hard to discover package manager

### ISSUE THREAD

**Issue by adambom** [forio/julia-studio#46]
Looking at 0.2.3 it's hard to figure out how to open the package manager pane.

**Comment by WestleyArgentum** [comment]
In 0.2.3 I actually changed the panes to, by default, open and show the file system and the package manager.

If you've had a version of the ide, however, then you'll have saved settings relating to which panes to have open... If you want to see what it looks like for a first time user you can `rm -r ~/.config/JuliaStudio`
