### ISSUE TITLE
Tab completion in console

### ISSUE THREAD

**Issue by adambom** [forio/julia-studio#53]
It works in the readline repl now, so we can make it work in Julia studio?

**Comment by phaebz** [comment]
Just wanted to open this issue with Julia Studio 0.4.2 on OSX 10.8.5. Are there news on this front?

**Comment by stuinzuri** [comment]
This is important to us and is on our list of things to do.  We can't give you a timeline other than "soonish".  Once this is in place you'll be one of the first to know.

**Comment by stuinzuri** [comment]
Upcoming in the 0.4.5 release due in two weeks or so.
