### ISSUE TITLE
Vertical alignment of text is weird with non-standard font size

### ISSUE THREAD

**Issue by adambom** [forio/julia-studio#54]
Have my font size set to 14 px
![Screen shot 2013-01-29 at 5 12 10 PM](https://f.cloud.github.com/assets/294597/109358/3eb7d476-6a7a-11e2-8a88-7920e32f8ae4.png)

**Comment by WestleyArgentum** [comment]
Apparently they fixed this in the new version of qt. We should upgrade

**Comment by WestleyArgentum** [comment]
Will be addressed by: #141

**Comment by WestleyArgentum** [comment]
Looks like this is fixed in the Qt5 port!
