### ISSUE TITLE
License mismatch

### ISSUE THREAD

**Issue by andrioni** [forio/julia-studio#56]
The [COPYING](https://github.com/forio/julia-studio/blob/master/COPYING) file says you are using LGPL 2.1, but [CONTRIBUTING.md](https://github.com/forio/julia-studio/blob/master/CONTRIBUTING.md) says it's GPL v3.

**Comment by WestleyArgentum** [comment]
Wow, thank you very much. In retrospect that's probably the most humorous copy paste error I've committed...

Just to clarify, the contributing file was correct, we did decide to go gpl v3.

**Comment by binarybana** [comment]
It'd be nice to have the GPLv3 in a LICENSE file, as it took me a while to find this in CONTRIBUTING.

**Comment by WestleyArgentum** [comment]
I think LICENSE jumps out more than COPYING, actually. I'll change that.
