### ISSUE TITLE
julia-specific features

### ISSUE THREAD

**Issue by andrioni** [forio/julia-studio#57]
Hi, it seems that the julia-specific features of JuliaStudio are missing when compiling from scratch, like syntax highlighting and recognition of julia files :)

As an example, here's the new file window:
![2013-02-04-191825_1920x1080_scrot](https://f.cloud.github.com/assets/159177/125320/e2640744-6f10-11e2-8929-5c0eb0346adf.png)

(though the text rendering on my compiled version is much prettier than on the binary version, for reasons unknown)

**Comment by WestleyArgentum** [comment]
It's good to know that rendering is nicer when you build it. I was never sure if it looked as bad on other machines as it does on the ubuntu virtual box that I use to build it... I figured it must be incompatibility with my screen, but maybe I need to update whatever libraries it depends on.

Anyway, I've started to suspect that the last couple issues are related to a little hack in `juliaeditor.pro`. On line 19 is a relative path set up for debug mode, it looks like we had trouble with a config check for release. I can tell you right now, if the target folder for the build is not named properly the julia specific things aren't getting deployed right.

Can you see if that code is in any way inconsistent with your setup? I'm going to figure out a better way to write it

**Comment by andrioni** [comment]
I probably won't be able to do that before tomorrow, but don't worry, I'll keep bothering you with more issues :)

**Comment by WestleyArgentum** [comment]
No worries at all. I think I fixed it to be generic here but I'm testing with a clean build before I commit.

**Comment by WestleyArgentum** [comment]
Try with cf19b2a42a358e0b31133c9e2454b1a52f2b0234, let me know if that helps

**Comment by adambom** [comment]
Is this fixed?

**Comment by andrioni** [comment]
Again, sorry for the delay, fixed.

**Comment by adambom** [comment]
Thanks. We've had some trouble with linux builds as you can see.

With any luck we'll have a debian package soon #69
