### ISSUE TITLE
Expression output for array comprehensions do not persist

### ISSUE THREAD

**Issue by adambom** [forio/julia-studio#62]
``` Julia
a = [n + rand() for n = 1:1000]
# Generates output
# ....
# Then
a
```

Errs with a is not defined.

Getting a similar problem with anonymous functions

**Comment by adambom** [comment]
This only applies when the command is entered into the console

**Comment by WestleyArgentum** [comment]
At the moment, I'm thinking the issue is: https://github.com/JuliaLang/julia/issues/2211

I could be wrong, we'll see.
