### ISSUE TITLE
Options - theme color 

### ISSUE THREAD

**Issue by ifed1** [forio/julia-studio#78]
The theme colors displayed are too dark compared to the color pallet.  

![color-pallet](https://f.cloud.github.com/assets/3228845/182225/bfb55372-7c69-11e2-9dde-e2d95eebd312.jpg)

**Comment by WestleyArgentum** [comment]
It looks like they use the color you pick as a base and apply shading dynamically. Since the shading is dynamic I think that's a reasonable approach. Maybe they could show you a box that's shades in various ways, but I don't think we should mess with this.
