### ISSUE TITLE
Install name of Julia Studio in applicaitons directory is JuliaStudio

### ISSUE THREAD

**Issue by mpbean** [forio/julia-studio#80]
Include a space in the applications directory for Julia Studio. Currently it appears as JuliaStudio. See image.

![name](https://f.cloud.github.com/assets/1878628/195645/02a13abe-7ffa-11e2-9f53-d8c47f2775a1.jpg)

**Comment by adambom** [comment]
+1 on this Wes. I know you don't like spaces in application names but it looks silly like this. 90% of our users are not going to be typing the name in the console anyway.

**Comment by keesvp** [comment]
---> #162 and #166
