### ISSUE TITLE
Console should accept multi-line input

### ISSUE THREAD

**Issue by adambom** [forio/julia-studio#81]
Currently fails with unexpected input error

**Comment by waldyrious** [comment]
Maybe this should be reopened? I'm getting a parse error:

```
julia> a = [1,
2]
ParseError("missing separator in array expression")
```

version: Julia Studio 0.3.0 Built on Feb 25 2013 at 09:22:04
OS: Windows7 32bit

**Comment by WestleyArgentum** [comment]
Ah, this was closed before I had committed the fix publicly. As of the latest changes 49e39954835beaf609f6afc838bd45bfe3aed228 it should be fine. If you pull and build again, does it work?

**Comment by waldyrious** [comment]
I didn't build from source, I'm testing the release version (the program prompted me to do so when I opened the previous version that I had installed, 0.2.4 I think).

**Comment by waldyrious** [comment]
(perhaps the version string could indicate whether the current install was built locally or downloaded as a precompiled binary)

**Comment by WestleyArgentum** [comment]
Not a bad idea. In the meantime, unfortunately, the fix for this is only in source. I'm sure we'll put up some new binaries soon-ish... but feel free to build in the meantime :)

**Comment by waldyrious** [comment]
oh, don't worry, it doesn't bother me a lot, I just wanted to report it so you guys would be aware of it :)

**Comment by adambom** [comment]
We should be able to deploy today, right? We haven't had a chance to QA 0.3.1 thoroughly, but I've been using it and it seems ok

**Comment by WestleyArgentum** [comment]
Ya, why not, let's do it. Maybe we can even get a couple other minor fixes in.

**Comment by waldyrious** [comment]
Can you mention the version where this was fixed? I'm still getting this:

```
a = [1,
2]
syntax: missing separator in array expression
```

Using version 0.3.1, built on Mar 5 2013 at 17:19:03 (the latest stable in Windows, according to http://forio.com/julia/downloads/)

**Comment by WestleyArgentum** [comment]
Interesting, I can replicate on windows but not mac. Must have missed something, I'll check it out

**Comment by waldyrious** [comment]
I'm sure you took this into account, but just in case: mac seems to be the only platform where the stable version is 0.3.2 rather than 0.3.1

**Comment by adambom** [comment]
Yeah we bumped the Mac version because we patched a problem with initializing git. Shouldn't affect the multi-line input.

**Comment by kbrydges** [comment]
QA note: I validated on Mac that multi-line input is accepted now.

**Comment by ifed1** [comment]
QA note: I verified this issue accepts multi-line inputs, however I could not do it right on the console. I had to use textpad to utilize text wrapped inputs, copy and paste the content into the console.

**Comment by ifed1** [comment]
Shift + Enter works for multi-line inputs in the console. Win7(64-bit)
