### ISSUE TITLE
Add ability to respond to prompts from julia

### ISSUE THREAD

**Issue by adambom** [forio/julia-studio#83]
For example, when installing Winston, it prompts me on how I want to install its dependencies. This prompt gets swallowed inside the JS console, and I can't input anything, so the installation fails.

**Comment by adambom** [comment]
The workaround for this is as follows:

Run the julia binary:
/Applications/JuliaStudio.app/julia/bin/julia-release-readline

or for Windows:
C:\Program Files (x86)\JuliaStudio-[version-number]\julia-studio\julia\bin\julia-release-readline

Then 
Pkg.rm("messed-up-package")
Pkg.add("messed-up-package")

Follow the prompts and when it's done close the process and return to Julia Studio.

**Comment by adambom** [comment]
This seems to be affecting a lot of people. We should fix ASAP.

**Comment by keesvp** [comment]
no longer relevant
