### ISSUE TITLE
Icon for Linux

### ISSUE THREAD

**Issue by andrioni** [forio/julia-studio#86]
I'm the maintainer of the JuliaStudio's PKGBUILD, and I'd like to know if you are planning to create some icons for the Julia Studio, I'm currently using the QtCreator one.

**Comment by adambom** [comment]
Does this help? I think I have AI too.

![icon_16x16](https://f.cloud.github.com/assets/294597/211873/d8ccb8b2-82c4-11e2-9356-84384bdca142.png)
![icon_16x16 2x](https://f.cloud.github.com/assets/294597/211874/d8dc74e6-82c4-11e2-8619-99465e24ef15.png)
![icon_24x24](https://f.cloud.github.com/assets/294597/211875/d8eedd5c-82c4-11e2-830d-15892db70eea.png)
![icon_128x128](https://f.cloud.github.com/assets/294597/211876/d8f14f4c-82c4-11e2-9559-00908e4efdea.png)
![icon_32x32](https://f.cloud.github.com/assets/294597/211877/d8f5f682-82c4-11e2-865c-5bc954d4e6af.png)
![icon_48x48](https://f.cloud.github.com/assets/294597/211878/d8f31d68-82c4-11e2-9966-a987f1012a9f.png)
![icon_128x128 2x](https://f.cloud.github.com/assets/294597/211879/d8eed762-82c4-11e2-982a-a39c12288a0f.png)
![icon_32x32 2x](https://f.cloud.github.com/assets/294597/211880/d8f4ce9c-82c4-11e2-92f9-20ade6ab472e.png)
![icon_512x512](https://f.cloud.github.com/assets/294597/211881/d9022d6c-82c4-11e2-9465-8daf3f394f22.png)
![icon_512x512 2x](https://f.cloud.github.com/assets/294597/211882/d90896ac-82c4-11e2-899a-81bf8f650e1b.png)
![icon_256x256 2x](https://f.cloud.github.com/assets/294597/211883/d92e33ee-82c4-11e2-9d6f-5e51d1ca855c.png)

**Comment by WestleyArgentum** [comment]
Is this done?

**Comment by andrioni** [comment]
Those are surely good enough, but if JuliaStudio just sent them to `INSTALL_ROOT/share/icons/hicolor/` as QtCreator already does would be better than doing it manually in the PKGBUILD for Arch Linux.

**Comment by WestleyArgentum** [comment]
I think this resolves the issue, but let me know if there are icons I missed

**Comment by WestleyArgentum** [comment]
I think this was resolved above

**Comment by andrioni** [comment]
Oh, sorry, I forgot to close the issue!
