### ISSUE TITLE
scope issue 

### ISSUE THREAD

**Issue by gregzuro** [forio/julia-studio#87]
Not sure if this is related to #85.
# parent.jl

include("child.jl")
GLOB="this is some text"
child.foo()
# child.jl

module child
foo()= println("the answer is: ", Main.GLOB)
end # module
# in plain old julia:

gz21:bin gregz$ pwd
/Applications/JuliaStudio.app/julia/bin
gz21:bin gregz$ ./julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" to list help topics
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.1.0+110332400.ra15d
 _/ |\__'_|_|_|__'_|  |  Commit a15dfa7a59 (2013-02-20 09:02:26)
|__/                   |

julia> cd("/Users/gregz/Desktop/code/julia")

julia> include("parent.jl")
the answer is: this is some text

julia> 
# in JS console:

<reset>
julia> VERSION
v"0.1.0+110332400.ra15d"

julia> pwd()
"/Users/gregz/Desktop/code/julia"

julia> include("parent.jl")
could not open file /Applications/JuliaStudio.app/Contents/Resources/juliaengine/parent.jl

julia> include("/Users/gregz/Desktop/code/julia/parent.jl")
GLOB not defined
at /Users/gregz/Desktop/code/julia/parent.jl:3

julia> 
# note that there is also the issue of include looking in the wrong place initially.

**Comment by WestleyArgentum** [comment]
we change paths dynamically now so that includes will work, also we have an issue for making the existing stuff work even better: #132
