### ISSUE TITLE
Console output is not suppressed with semicolon

### ISSUE THREAD

**Issue by gregzuro** [forio/julia-studio#97]
"Once the user has entered a complete expression, such as 1 + 2, and hits enter, the interactive session evaluates the expression and shows its value. If an expression is entered into an interactive session with a trailing semicolon, its value is not shown."

In 

Julia Studio 0.3.1 
Based on Qt 4.8.4 (32 bit)

Built on Mar 5 2013 at 17:19:03

this happens:

julia> 1+2
3

julia> 1+2;
3

julia> 

The '3' should not appear with the semicolon.  Doing the same thing in the -readline and -basic .exe files (windows 7 64bit machine) shows the correct behavior (suppressed).

**Comment by WestleyArgentum** [comment]
Fair point, good catch

**Comment by ifed1** [comment]
julia> 1+2;

julia> 1-2
-1

julia> 1+2
3

verified with win7(64-bit)
