### ISSUE TITLE
Installer crash on os x

### ISSUE THREAD

**Issue by Staross** [forio/julia-studio#99]
The installer just crash on my 10.5.8 Os X laptop:

Model: MacBookPro2,2, BootROM MBP22.00A5.B07, 2 processors, Intel Core 2 Duo, 2.33 GHz, 2 GB
Graphics: kHW_ATIr520Item, ATY,RadeonX1600, spdisplays_pcie_device, 256 MB

Process:         JuliaStudio [22819]
Path:            /Volumes/julia-studio-macx-installer-0.3.1/JuliaStudio.app/Contents/MacOS/JuliaStudio
Identifier:      com.forio.juliastudio
Version:         ??? (???)
Code Type:       X86-64 (Native)
Parent Process:  launchd [112]

Interval Since Last Report:          27281462 sec
Crashes Since Last Report:           74
Per-App Interval Since Last Report:  0 sec
Per-App Crashes Since Last Report:   2

Date/Time:       2013-03-15 17:05:07.636 +0100
OS Version:      Mac OS X 10.5.8 (9L31a)
Report Version:  6
Anonymous UUID:  6944C357-5A7A-4063-951E-E64CD8BE0675

Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000002, 0x0000000000000000
Crashed Thread:  0

Dyld Error Message:
  Symbol not found: _OBJC_CLASS_$_CALayerHost
  Referenced from: /Volumes/julia-studio-macx-installer-0.3.1/JuliaStudio.app/Contents/MacOS/../Frameworks/QtWebKit.framework/Versions/4/QtWebKit
  Expected in: /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore

**Comment by WestleyArgentum** [comment]
I hate to say it but we no longer support pre Snow Leopard. Sorry to mislead you, I see we listed support for 10.5 in the readme.

Out of curiosity, does vanilla Julia run on your system?

**Comment by Staross** [comment]
Unsurprisingly it doesn't :)

You should just put the system requirement on the download page for each system, I didn't saw any readme on the way. I got another 10.6.8 mac and it runs well on it.

**Comment by adambom** [comment]
@Staross will do
